target  = 'bst_test'
sources = [Glob('bst_test.c'),
           Glob('../bst/*.c'),
           Glob('../util/*.c'),
           ]
env = Environment(CPPFLAGS=['-Wall', '-g', '-O2', '-std=c99'],
                  LIBS=['cunit'],
                  CPPPATH=['../util', '../bst'],
                  )
test       = env.Program(target, sources)
test_alias = env.Alias('check', test, test[0].abspath)
env.AlwaysBuild(test_alias)
